### ISSUE TITLE
3.0 Release not showing rich presence.

### ISSUE THREAD

**Issue by empdarkness** [Krognol/discordify#2]
When using your 3.0 release for windows, no matter what i try, it will not show any rich presence. When i switch back to your 2.0 release, it works perfectly fine. Have no idea what it may be.

**Comment by Krognol** [comment]
I think another person had the same issue, and I think I know what the problem is. I'll put up a new release soon.

**Comment by Krognol** [comment]
Check out release 3.1. And verify that it's fixed.

**Comment by nitrog0d** [comment]
Where? lol.

**Comment by Krognol** [comment]
[Here](https://github.com/Krognol/discordify/releases/tag/3.1). Sorry, accidentally clicked the wrong button.
