### ISSUE TITLE
discordify.exe doesn't open.

### ISSUE THREAD

**Issue by toneehh** [Krognol/discordify#6]
I tried building the file and it built with no errors (I think at least, I've never done this before) but when I try to open discordify.exe in the debug folder, nothing happens. 

1>------ Rebuild All started: Project: discordify, Configuration: Debug Any CPU ------
1>  discordify -> C:\Users\Toni\discordify\discordify\bin\Debug\discordify.exe
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

https://i.imgur.com/GJee6bi.png

**Comment by Krognol** [comment]
Try placing the `discord-rpc-w32.dll` from the `lib` folder in your `Debug` folder.

**Comment by toneehh** [comment]
Still doesn't work. I tried running as an admin too, nothing.

**Comment by Krognol** [comment]
Can you try downloading one of the release builds and see if they launch?

**Comment by Jonathing** [comment]
I have the same problem. I opened the Discordify.exe application and I look into Task Manager. It closes itself after about 2 seconds. I'm going to try debugging it and see if I get anything.

**Comment by Jonathing** [comment]
I found the cause of the issue, or at least what Visual Studio says to be the cause. It looks like not everything is being exported into the Debug folder when it is built.
![https://i.imgur.com/Vsg1rIT.png](https://i.imgur.com/Vsg1rIT.png)

**Comment by Jonathing** [comment]
When I put the Resources folder in the Debug folder, the application loads!
![https://i.imgur.com/TUScKbX.png](https://i.imgur.com/TUScKbX.png)
