### ISSUE TITLE
Newtonsoft.Json not found

### ISSUE THREAD

**Issue by Jonathing** [Krognol/discordify#8]
![https://i.imgur.com/wcU5bOD.png](https://i.imgur.com/wcU5bOD.png)
And the following shows up in Visual Studio:
`
1>------ Build started: Project: discordify, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1988,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Newtonsoft.Json". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
1>  discordify -> D:\Users\jonat\gitother\discordify\discordify\bin\Debug\discordify.exe
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========`

**Comment by Jonathing** [comment]
I'm using the master branch; I directly cloned Discordify.

**Comment by odevine** [comment]
Fixed this by installing newtonsoft.json directly via nuget and then rebuilding the solution

**Comment by Krognol** [comment]
Newtonsoft.Json should be linked in the solution, but install it via Nuget, as suggested by odevine.

**Comment by Jonathing** [comment]
Then include that in the readme in case others have the same problem in the future.
